# Task level variable
- name: variables from PLAY level
  hosts: localhost
  vars: 
    Course: "Devops"
    Trainer: "siva"
    Duration: "110HRS"
  tasks:
  - name: check variables
    vars:  # task level
      Course: "Devops with AWS"
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}"
