- name: Variables from play level
  hosts: localhosts
  vars_files:
  - variables.yaml
  vars_prompt:
  - name: PERSONS
    prompt: Please eneter your name
    private: false
  - name: WISHES
    prompt: Please enter your wishes
    private: false
  vars: 
    PERSONS: "siva from play"
    WISHES: "Morning from play"
  tasks:
  - name: check variables
    vars:
      PERSONS: "siva from task"
      WISHES: "Morning from task"
    ansible.builtin.debug:
      msg:"Hello {{PERSONS}}, Good {{WISHES}}"


# 1. CMD line
# 2. task level
# 3. files
# 4. prompt
# 5. play level
# 6. inventory
# 7. roles